# Generated by Django 5.2.7 on 2026-06-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0036_grupo_listo_f2_tematicas"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreguntaRompehielo",
            fields=[
                ("idpregunta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_equipo",
                    models.CharField(
                        choices=[
                            ("desconocidos", "Personas que no se conocen"),
                            ("conocidos", "Personas conocidas"),
                        ],
                        default="desconocidos",
                        max_length=20,
                    ),
                ),
                ("texto", models.TextField()),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pregunta_rompehielo",
                "ordering": ["tipo_equipo", "orden", "idpregunta"],
            },
        ),
    ]
