# Generated by Django 5.2.7 on 2026-07-26 20:37

import django.db.models.deletion
import juego.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0037_preguntarompehielo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sesion",
            name="drive_carpeta_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="FotoEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_temporal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=juego.models.ruta_foto_equipo_temporal,
                    ),
                ),
                ("drive_carpeta_id", models.CharField(blank=True, max_length=255)),
                ("drive_foto_id", models.CharField(blank=True, max_length=255)),
                ("drive_txt_id", models.CharField(blank=True, max_length=255)),
                ("nombre_archivo", models.CharField(blank=True, max_length=255)),
                ("integrantes_snapshot", models.JSONField(blank=True, default=list)),
                ("subida_drive", models.BooleanField(default=False)),
                ("error_drive", models.TextField(blank=True)),
                ("fecha_captura", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foto_equipo",
                        to="juego.grupo",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos_equipo",
                        to="juego.sesion",
                    ),
                ),
            ],
            options={
                "db_table": "foto_equipo",
            },
        ),
    ]
