# Generated by Django 5.2.7 on 2026-07-30 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0038_sesion_drive_carpeta_id_fotoequipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preguntarompehielo",
            options={
                "ordering": ["tipo_equipo", "tipo_pregunta", "orden", "idpregunta"]
            },
        ),
        migrations.AddField(
            model_name="grupo",
            name="modo_conocidos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("desconocidos", "Personas que no se conocen"),
                    ("conocidos", "Personas conocidas"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="pregunta_rompehielo_asignada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_asignados",
                to="juego.preguntarompehielo",
            ),
        ),
        migrations.AddField(
            model_name="preguntarompehielo",
            name="tipo_pregunta",
            field=models.CharField(
                choices=[("base", "Pregunta base"), ("pool", "Pregunta aleatoria")],
                default="pool",
                max_length=10,
            ),
        ),
    ]
