# Generated by Django 5.2.7 on 2026-08-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0040_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoequipo',
            name='seleccionada_galeria',
            field=models.BooleanField(default=False, help_text='Marca si el admin eligió esta foto para mostrarla en la galería de equipos previa a la reflexión final. La selección es global y aplica a todas las sesiones hasta que se cambie.'),
        ),
    ]
