# Generated by Django 5.2.7 on 2026-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0041_fotoequipo_seleccionada_galeria"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneDriveAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_cache_encriptado", models.TextField(blank=True, default="")),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "onedrive_auth",
            },
        ),
    ]
