# Generated by Django 5.2.7 on 2026-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juego", "0042_onedriveauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotoequipo",
            name="error_onedrive",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fotoequipo",
            name="onedrive_carpeta_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fotoequipo",
            name="onedrive_foto_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fotoequipo",
            name="onedrive_txt_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fotoequipo",
            name="subida_onedrive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sesion",
            name="onedrive_carpeta_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
