# Generated by Django 5.2.7 on 2026-08-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0043_fotoequipo_error_onedrive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='t_diferencias',
            field=models.IntegerField(default=240),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='t_empatia',
            field=models.IntegerField(default=360),
        ),
    ]
